### ISSUE TITLE
autenticación según videos de la clase

### ISSUE THREAD

**Issue by stealth14** [DAW-ESFOT/proyecto-grupal-policrushes#4]

**Comment by jovv1994** [comment]
Pasos en la autenticación:
1.- El usuario debe llenar el formulario de usuario y contraseña para iniciar sesión en el navegador(cliente).
2.- Se envía el formulario a través de POST haciendo referencia al endpoint.
3.- El servidor recibe esta petición con los datos del formulario.
4.- Se valida la información en la base de datos
5.- El servidor crea un token JWT si la información de usuario y contraseña es valido utilizando una clave de cifrado.
6.- Una vez generado el token el servidor responde al cliente con el token.
7.- El cliente tiene que almacenar el token para las nuevas peticiones posteriores que necesite realizar.
8.- Se envía la petición junto con el token que esta incluida en una cabecera de authorization.
9.- El servidor recibe la petición y evalúa si es que existe o no existe un token.
10.- Si es que existe un token el servidor lo valida y si todo esta en orden obtiene la información y la devuelve al cliente.
11.- En el caso de que el usuario no envié un token el servidor le devuelve un código http correspondiente.
